"""
Finite Element Analysis (FEA) module for VOLCO.

This module provides functionality to perform structural analysis on voxel models
generated by VOLCO simulations, including saving and loading analysis results.
"""

# Core functionality
from .core import analyze_voxel_matrix, load_fea_results

# Visualization
from .viz import visualize_fea, export_visualization, visualize_voxel_matrix

# Boundary conditions
from .boundary import (
    Surface,
    select_nodes_by_predicate,
    select_nodes_in_box,
    select_nodes_on_plane,
    select_nodes_by_position
)

# I/O operations
from .io import save_results, load_results

# Analysis utilities
from .analysis import (
    compute_midplane_force,
    compute_face_displacement_jump,
    compute_effective_stress,
    compute_effective_modulus,
    average_strain_component,
    get_cell_lengths,
    get_cell_volume
)

__all__ = [
    # Core functionality
    'analyze_voxel_matrix',
    'load_fea_results',
    
    # Visualization
    'visualize_fea',
    'export_visualization',
    'visualize_voxel_matrix',
    
    # Boundary conditions
    'Surface',
    'select_nodes_by_predicate',
    'select_nodes_in_box',
    'select_nodes_on_plane',
    'select_nodes_by_position',
    
    # I/O operations
    'save_results',
    'load_results',
    
    # Analysis utilities
    'compute_midplane_force',
    'compute_face_displacement_jump',
    'compute_effective_stress',
    'compute_effective_modulus',
    'average_strain_component',
    'get_cell_lengths',
    'get_cell_volume'
]